Dating has gone mainstream as a topic these days. from Instagram to comments like “where all the good men have gone” or topics like feminism trending on Twitter, everyone seems to be talking about it.

Over the last few years, I have distributed more and more time to my dating life, doesn’t mean I necesarrily took it more seriously, but I found myself spending a lot of time trying to understand how to attract girls into my life. Until Covid hit, I would be doing daily cold approaches on the street and frequent the shopping mall in my town browsing and looking for excuses to talk to girls. Although, I was having my fair share of results, I couldn’t scratch an itch that always fascinated me. I wanted to actually understand what sort of relationship does money and fame actually have on your dating life. 

So Covid gave me a great opportunity to do just that, online. But before we get into that, let’s set some things straight.

First let’s talk about fame.  Fame is such a broad term. For example, you can be famous within a circle that doesn’t really correlate to dating success. For example, I am sure the CEO or CTO of Coca Cola, is a famous man within the business circles, probably recognized in conferences and many people want to pitch him their ideas for collaboration or investment. But, I doubt many girls would fangirl over him if he walked alone in a club. On the same boat, seems to be someone who’s famous for the wrong reasons, like a viral embarassing youtube video. He might get recognized and people may even ask for a photograph, but that doesn’t correlate to getting higher chances of pulling a girl.

# Fame vs “Being Recognizable”

There’s a difference between the two though, being famous and being recognizable are two different thing. For you to benefit, you should be recognizable. So there are three types of “recognition”. First one is being wildly famous, think a celebrity in your country that can walk into any room and someone will always go “omg that’s X.” or will at least walk up to him and be like “do I know you from somewhere??” The second way is being regionally famous for something “cool” for example, there are some regional musicians that are very well known in a few cities around a county that people sort of seen them perform here and there and will recognize them out and about. The third way is to be recognizable within a subset of people, like a community, maybe you well known for organizing an event or being the spokeperson for a group or something, that’s best done online but if you find something like dancing, circling or something that women are also involved in, this can get you recognized somewhere.

Now let’s look at the other thing, money. Money has to be displayed and spent for a guy to get attention off of them. If you walk up to a girl and go “Hi! I am a millionaire, wanna go hang out?” she would laugh...so the only way to influence someone’s opinion in dating, is sort of to display your wealth and spend money and since most of us don’t really have the money to do exactly that so much so that it will cause a constant stream of girls, I don’t see it as a value trade. 

## The Experiment

So let’s go with the experiement, it all started when I became aware of an online streaming platform named Twitch. At that moment in time, twitch had double its viewers in my home country just a few days after the first strict lockdown, it seemed like more than 250.000 people were watching semi-daily and for a country of 10 million people, it seemed like a big number. So I deviced a plan. Since Twitch is a gaming platform and gaming let’s not lie here is heavily dominated by a male viewer base, I estimated the ratio of girls on the platform to be around 1 in 1000. So for every 1000 users there was roughly, 1 girl and 999 guys on the site. This is my rough ballpark estimate, from what I have seen in my country and not an official statistic, but even if those estimates are wrong, it’s not look like a prime place to flirt huh? Imagine Twitch was a physical club, you walk in and see, a giant dance floor, with males, pushed against each other, holding a drink, as a single girl on the entire place is squeezed in between them, you would probably turn around and go somewhere else. But, because unlike the real world, A) People were not there to flirt, this meant that girls were more tolerant with people approaching them, giving them the benefit of the doubt. B) I or them were not limited to talking to one person at a time, like in real life, meaing I could easily shoot my shot and move to the next girl until she comes back to me. B) People were spending a lot of time in the platform and forming a community, where most recurring members would know of each other, unlike a club where you sort of have one chance and probably won’t see the girl again.

So I started to formulate a plan to taste my hypothesis about “recognition” and money.  I created an account and sort of frequented a few streams, I wouldn’t type, I would just scan the chatrooms for female usernames, look at their pictures, discard the ones without a picture, or visibly looked under 18, then reverse image search their pictue to make sure it’s not a famous artist or whatever and then send them a private message and get busy finding another one. To those who replied, I would quickly ask for age to make sure they were over 18, and then keep flirting. I started keeping records of the girls I dm’ed and how many of them replied. By the end of the month, I had send a message to 100 girls and 20 of them replied. So 20 girls out of 100 was my total “cold approach” numbers. They didn’t know me, I didn’t know them, they just saw a picture and I saw a picture. It the equivalent of looking at each other on a street and stricking up a conversation.

The next month, I did the following. I frequented a few more streams and would look again for female username, do the same process, but instead of directly messaging them, I would look for their comments and find an opporunity to reply to them tagging them publicly on the chatroom, and say something funny or intruging to them. But type nothing to none at all, even if some guy tagged me, I wouldn’t borther replying. Ι would only reply to the girls, then after a few back and forths in public or when I was feeling the momentum was towards me, like she laughed at a joke or something, I would continue the conversation by a dm. Even the girl was not interested from the first tag or didn’t reply positively, 99% of the time, I would just drop my interest in her and move to another girl. At the end of the month I had dm’ed 100 girls this way too. The result from this method were slightly positive out of 100 girls 29 replied. So that’s a 29% final rating. This way I wanted to simulate knowing each other directly before approaching. Like let’s say you and a girl go to the same gym or frequent a same store and seen each other a few times but never talked or flirted. So she has previous direct knowledge of you as part of a community or something.

Now for the next month, I wanted to spend a month to build some “reputation” and test that, so I started talking to a few streamers, talking to a few other male viewers, build some friendships and show a bit of my character and my humor on those streams. I made a few casual acquintances, maybe a few friends even but nothing that made my name well known in the community or something. Over the course of the month, I didn’t talk to any new girl, just casually kept chatting with the girls I already had a vibe with and focused on building my “reputation”. When the building process was sort of done for the month, I spend the following month texting those guys I met for “references” asking maybe them about girls I saw frequent the chartoom which I hadn’t yet spoken to, if they knew them or what’s the vibe and then sort of approached them as a friend of a friend. I wanted to simulate meeting girls through your friend group. Being the familiar guy you seen by don’t know directly, but someone you know can vouch for him. I approached 100 girls this way again and found that 44 replied. Out of those 100, none was underage, since guys were kind enough to tell me who of those they knew, were so.

For the next sort of “experiment” I wanted to try money as a sort of way of gaining recognition. Similar to buying followers on Instagram or buying ads for people to see your youtube channel, right? Sort of build a name for myself. So I found two streamers, both male, because I didn’t want to make it obviously targeted at females, so I avoided female steamers who would casually have a bigger female crowd. One of the streams were big for my country, but also a bit “edgy” and almost exclusively male dominated, and when I saw male dominated, out of the 1000 people on his chartoom at any one time maybe 1 was a girl and tha was his girlfriend as I later learned. The other streamer, was more female friendly having a few girls in his chat at any one time, probably the biggest percentage out of all the other male streamers, I examined, but was very small, averaging less than 100 viewers at most streams at any one time. So, my plan was to gift sub (because of the badge which made my name more recognizable in chatroom) a few hundreds of subs in both over the course of a 6 month period, frequently being in the top spots to boost my name to the maximum amount of female viewers and having the streamer broadcast my name on several occasion. Result was admirable, just 1000 euros in , most of the moderators of those channels were knew me, some really liked me and befriended me, as well as many casual viewers filling my dms with kindness worlds and praising me for helping those people make a decent living. My fame on those chatrooms grew so much, I decided towards the end to sort of do a few subs  to other channels, big and small and spread my name a little bit more. By the end of the 6 months, I was a moderator in 9 different channels, averaging from 1.200 viewers to just over a 100. Most people knew my name, I made friendships with names that had been in the community for years and would vouch for me with their friends and I started flirting again. 

I texted 100 girls after my newly gained “recognition” and 72 out of the 100 girls replied to my dm. That’s close to a 30% improvement from my most successful of the other 3 methods. Now, I don’t know how 3000 sounds to you, but for me it’s neither petty cash nor a huge amount. It’s about 3-4 month salary for a young person, as the average salary is 600 a month. So spending 3000 over 6 months, is still spending the majority of your salary, but it’s not an amount anyone girl would go crazy for. I think most of the excitement was because to spend 3.000 on something as insignicant as fame and most of all fame on a gaming platform, seems ridiculous to most people. As far as I understound, for most people seeing this was like sending 3.000 in charity, they were both “who is this guy that can afford that?” thinking it will go beyond that, because they didn’t see it stop for 6 months, so they maginified it, and also, most of them were below 30, which to them this amount seemed a huge deal. Lastly, they enjoyed themselves and had heard how difficult it is for  small streamers to get by, that they were overwhelmed this journey would continue and sort of equaled their opinion of me, with the opinion of their steamer they were admiring. It was such a weird feeling for someone who doesn’t really play games anymore or can vibe with the craze of that community filled with 20 year olds. 

Now, the last part of the experiement, since this is a dating experiement, you would think what happened of all those girls you texted? Well, let’s look at some results

from the 18 girls who replied to my cold approach method 14 of them had “sex” with me. Now let’s identify what I think of “sex” with quotes. For me, having “sex” in this study consitutes as a girl, either, offering to connect with me on a non-anonymous platform like asking for my instagram and following each other there, then keep flriting and sexting over instagram...or b) sending me a nude in which her face is attached or c) giving detailed descriptions of sexual activity with me to make me jerk off for her and of course physically going on a date and actually having sex...duhhhhhhhhhh

So cold approach 8 out of 20 (40%). Second method 5 out of 29 (17%). 10 out of 44 (22%) and finally the recognition method which landed me 25 out of 77 (32%). So, my way of seeing those results is that, yes, doing more work, being a friendly face, having recognition or being a friend of a friend. In general, if a girl has previous knowledge of who you are, it will increase your chances of receiving a reply, although if you want casualy sex, at least on the internet, or on a platform like twitch, approacing girls cold approach will land the best results. That’s assumining you having texting skills. I must say that these data are not universal, not by a landslide. But it should give you a ballpark range of where you should expect those different methods to hit in terms of getting you a reply from a girl. 

Additional info that you find some value on is , that I didn’t send a “hi, how are you?” or something lame like that to any of the girls, but I didn’t stick to a pick-up line either. I quickly understood that on twitch you should sort of tailor your message to the girl, although one message that sort of proved useful or “common” implying it was used like 5-10 times on this data set is the “hey, fancy seeing you on my friendlist :P how did you land in here?” followed up by a story about how I sometimes “missclick” on profiles watching steams from my tablet, when I experimented with added a few girls to my friendlist and waiting for them to add me back before whispering them.

I also did happen to get a one night stand, from a girl that happen to be in my city for a few days, we started chatting from twitch and went for a night out finally landing back in my place, but as you can see if you looking for soemthing more than the ocassional nude or live in a big capital of your country, therefore can transition to a date efficiently, I wouldn’t hit Twitch.

Hope you enjoyed 🙂
